site_name: Odoo Development Tutorials
repo_url: https://github.com/Multi-Academy/odoo-development-tutorials
repo_name: odoo-development-tutorials

theme:
  name: material
  font: 
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  
  palette:
    
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: purple
      accent: purples
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
        
  features:
    - navigation.footer
    - navigation.instant
    - content.code.copy
    - content.code.select
    - content.code.annotate 
    - content.tabs.link

plugins:
  - search
  - git-committers:
      repository: Multi-Academy/odoo-development-tutorials
      branch: main
  - git-authors
    - glightbox
  - git-revision-date-localized:
      enable_creation_date: true


markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
    - index.md
    - install_odoo.md
    - create_custom_module.md